- branch: master
  build: 125
  release_nottes:
  destinations: privateA
  mandatory_update: false
  notify_testers: true
  type: alpha
  prerelease: true
  draft: false
- branch: feature
  build: 125
  release_nottes:
  destinations: public
  mandatory_update: false
  notify_testers: True
  type: alpha
  prerelease: true
  draft: false
- branch: pull
  build: 125
  release_nottes:
  destinations: public
  mandatory_update: false
  notify_testers: true
  type: alpha
  prerelease: true
  draft: false
