- branch: master
  build: 125
  release_nottes:
  destinations: privateA, public, privateB
  mandatory_update: False
  notify_testers: True
- branch: feature
  build: 125
  release_nottes:
  destinations: privateA, public, privateB
  mandatory_update: False
  notify_testers: True
