- branch: master
  build: 125
  release_nottes:
  destinations: privateA
  mandatory_update: False
  notify_testers: True
- branch: feature
  build: 125
  release_nottes:
  destinations: public
  mandatory_update: False
  notify_testers: True
