name: build_on_PR

on: 
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Sign Android Release
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: build
        path: app/build/outputs/apk
        
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
    
    - name: Get commit message (1)
      uses: technote-space/get-git-comment-action@v1
    - name: Get commit message (2)
      run: |
            echo "${{ env.COMMIT_MESSAGE }}" > release_notes.txt
            cat release_notes.txt
            mv release_notes.txt app/build/outputs/apk/
      
    - name: Upload to Azure
      uses: fixpoint/azblob-upload-artifact@v3
      with:
        connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        name: build
        path: app/build/outputs/apk
    
    - name: Add label
      run: |
        pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        curl -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -d '{"labels": ["built-complete"]}' https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$pull_number/labels
      
    
      
