name: ChatOps
on: [issue_comment]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Listen for PR Comments
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: "/distribute"
        env: # you must supply GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: prcomm
      
      - name: Checking Out
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        uses: actions/checkout@v2
          
      - name: App Center
        id: cli
        run: |
          npm install appcenter-cli@2.3.3
          comment=$(npx appcenter distribute  ${{ steps.prcomm.outputs.TRAILING_LINE }} --token "${{secrets.APP_CENTER_TOKEN}}" -a ${{ secrets.APP_NAME }})
          echo $comment
          echo "::set-output name=comment::$comment"
          
      - run: |
          echo ${{ steps.cli.outputs.comment }}
          
      - name: Comment Action
        uses: JungWinter/comment@v1
        with:
          # create|edit
          type: create
          # comment body
          body: "${{ steps.cli.outputs.comment }}"
          # github token
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            "${{ steps.cli.outputs.comment }}"
