name: distribute_app
on: [issue_comment]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: listen for PR Comments
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: "/distribute-app"
        env: # you must supply GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: prcomm
      - name: checkout
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        uses: actions/checkout@v2
      - name: Download a Build Artifact from Azure Blob Storage
        uses: fixpoint/azblob-download-artifact@v3
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}      
          name: build
          path: build
      - uses: technote-space/get-git-comment-action@v1
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      - name: Get commit message
        run: |
              #zip -r build.zip app/build/outputs/apk/release
              echo "${{ env.COMMIT_MESSAGE }}" > release_notes.txt
              cat release_notes.txt
      - name: Distribute release
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        uses: ahdbilal/AppCenter-Github-Action@v1.0.3
        with:
          command: appcenter distribute release -f build/release/app-release-unsigned-signed.apk -a ahbilal-microsoft.com/firstApp -g privateA -R release_notes.txt
          token: ${{secrets.APP_CENTER_TOKEN}}
      - uses: andymckay/labeler@1.0.2
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          add-labels: "distribute complete"
          ignore-if-assigned: true

      
