# This is a basic workflow to help you get started with Actions

name: read_config

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell


    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
    
    - name: read_dist_config
      id: dist_config
      run: |
        pip install PyYAML
        echo $GITHUB_REF
        destinations=$(echo $GITHUB_REF | python3 .github/workflows/lib/read_dist_config.py "destinations")
        echo "::set-output name=destinations::$destinations"
        echo $destinations
    
    - name: Run a one-line script
      run: |
        echo ${{ steps.dist_config.outputs.destinations }}
        echo "${{ steps.dist_config.outputs.destinations }}"
        
        
        
        
        
    
