name: Android CI

on: 
  pull_request:
    branches: [master]
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
    - name: appcenter_cli
      run: |
        install_url=$(curl -X GET "https://api.appcenter.ms/v0.1/apps/ahbilal-microsoft.com/firstApp/distribution_groups/privateA/releases/latest" -H "accept: application/json" -H "X-API-Token: 48795f81b653dcbad31bbb403f21b49d538badb3" | python3 -c "import sys, json; print(json.load(sys.stdin)['install_url'])")
        echo "::set-env name=link::www.google.com"
    - run: |
        echo "${{steps.deploy.outputs.link}}"
    - name: QR Code Commenter
      uses: kentaro-m/qr-code-commenter-action@v0.1.2
      with:
        comment: |
          :lock: This is a QR code for access to the preview website.
          :iphone: Scan a code with your device.
          {qrcode}
        content:  www.google.com
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    
